[package]
name = "rev_backrooms"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = { version = "0.7.0", default-features = false, features = [
    "3d",
    "f32",
    "parry-f32",
    "parallel",
] }
bevy = { version = "0.19.0", default-features = false, features = [
    "std",
    "async_executor",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_gltf",
    "bevy_log",
    "bevy_pbr",
    "bevy_render",
    "bevy_scene",
    "bevy_winit",
    "jpeg",
    "keyboard",
    "mouse",
    "multi_threaded",
    "png",
    "reflect_auto_register",
] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
